### ISSUE TITLE
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1'

### ISSUE THREAD

**Issue by rmoff** [etolbakov/excalidocker-rs#3]
```
./excalidocker --input-path ~/git/lakeFS/deployments/compose/docker-compose.yml
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/main.rs:159:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Input file is [this one](https://github.com/treeverse/lakeFS/blob/master/deployments/compose/docker-compose.yml)

(`excalidocker` worked fine with [this one](https://github.com/treeverse/lakeFS-samples/blob/new-eb/docker-compose.yml))

**Comment by etolbakov** [comment]
Thanks @rmoff for the feedback. I'll take a look!
That was quick 😆
