### ISSUE TITLE
Suggestions :)

### ISSUE THREAD

**Issue by rmoff** [etolbakov/excalidocker-rs#4]
This is just brilliant, thank you! 

I saw your roadmap, FWIW I would put at #1 the Docker artefact - being able to run this without installing/building would make it super useful. It could then also be used in things like github actions for auto documentation as well. 

Other ideas: 

- [x] Echo the output path used; I was a bit confused when I ran it and nothing seemed to happen - I had to RTFM to find out it went to `/tmp` by default
- [x] Add ability to specify font used 
- [x] Add toggle for displaying dependencies
- [x] Use arrows instead of lines as connectors so that when boxes are moved the connections remain with them

**Comment by etolbakov** [comment]
That’s a great compliment @rmoff!
Thank you for the feedback/new ideas. Specifically, if you could elaborate "Add toggle for displaying dependencies" point?
Do you mean the ability to provide subset of containers from the compose file that you would like to include in the result excalidraw?

**Comment by rmoff** [comment]
> Add toggle for displaying dependencies

I mean whether to show the connecting lines or not, i.e. so it could just render each service without the lines to show dependencies

**Comment by etolbakov** [comment]
@rmoff 
docker image support (and Linux artifact as well) and toggle for displaying dependencies are ready.
As always your feedback is much appreciated 🙏
The next stop - is the "connected arrows" 🚌 🏃‍♂️

**Comment by etolbakov** [comment]
My release train missed the next stop and made its way to the very end 😅 
Closing this issue, please let me know if you find the utility working according to your expectations.
Thanks!
